jms_serializer:
  visitors:
    json_serialization:
      options: [JSON_UNESCAPED_SLASHES, JSON_UNESCAPED_UNICODE]
  object_constructors:
    doctrine:
      fallback_strategy: "null" # possible values ("null" | "exception" | "fallback")
  property_naming:
    id: 'jms_serializer.identical_property_naming_strategy'