nelmio_api_doc:
  areas:
    path_patterns: # an array of regexps
      - ^/api(?!/doc$)

    documentation:


      info:
        title: universal counter
        description: universal counter
        version: 1.0.0