version: '3'

services:
  php:
    container_name: php-fpm
    build: ./php-fpm
    ports:
      - ${DEV_SERVER_PORT}:9001
    volumes:
      - ../:/var/www/symfony:cached
      - ./logs/symfony:/var/www/symfony/var/log:cached
    depends_on:
      - db
    networks:
      - php
      - db

  db:
    image: postgres:11-alpine
    command: postgres -c work_mem=4GB -c max_parallel_workers_per_gather=8 -c max_connections=900
    shm_size: 8g
    ports:
      - '5432:5432'
    container_name: db
    working_dir: /app
    restart: always
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - ./data/postgresql:/var/lib/postgresql/data
    networks:
      - db

  nginx:
    container_name: nginx
    build: ./nginx
    ports:
      - "80:80"
    depends_on:
      - php
    networks:
      - php
    volumes:
      - ./logs/nginx:/var/log/nginx:cached
      - ../:/var/www/symfony:cached

networks:
  db:
  php:

